image: maven:3.6.1

pipelines:
  branches:
    master:  # Trigger this for any pushes to the master branch.
      - step:
          name: Build and Deploy Snapshot Artifact
          trigger: manual # automatic
          caches:
            - maven # Cache any dependencies we download, speeds up build times.
          script:
            - bash configure_maven.sh # Create our settings.xml file.  Will fail if environment variables aren't set properly.
            - git submodule update --init
            - mvn -B --file all-modules-build/pom.xml verify # Ensure all artifacts build successfully before we attempt deploy in order to prevent partial deploys.
            - mvn -B --file all-modules-build/pom.xml -DskipTests deploy # Now that all builds have completed, we can deploy all the artifacts.
          artifacts: # This will carry across the files you want to deploy to all subsequent steps
            - tip-wlan-opensync-wifi-controller/opensync-gateway-static-process/target/opensync-gateway-static-process-0.0.1-SNAPSHOT.jar
            - tip-wlan-cloud-services/all-cloud-in-one-process/target/all-cloud-in-one-process-0.0.1-SNAPSHOT.jar
      - step:
          name: Deploy to Test
          image: aneitayang/aws-cli:1.0
          deployment: Test
          trigger: manual
          script:
            - echo "Deploying to test ..."
            - aws --version
            - echo "Deploying to Bitbucket Downloads"
            - echo "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads"
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"tip-wlan-opensync-wifi-controller/opensync-gateway-static-process/target/opensync-gateway-static-process-0.0.1-SNAPSHOT.jar"  
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"tip-wlan-cloud-services/all-cloud-in-one-process/target/all-cloud-in-one-process-0.0.1-SNAPSHOT.jar"  

