name: Java Maven CI - TIP WLAN Cloud Master

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_AUTOMATION_KEY }}
          submodules: true
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          server-id: tip-wlan-cloud-maven-repo # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_REPO_USERNAME # env variable for username in deploy
          server-password: MAVEN_REPO_PASSWORD # env variable for password in deploy
      - name: maven version
        run:
          mvn -v
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
      - name: Login to TIP Docker registry 
        uses: azure/docker-login@v1
        with:
          login-server: tip-tip-wlan-cloud-docker-repo.jfrog.io
          username: build-pipeline
          password: ${{ secrets.MAVEN_REPO_PASSWORD }}
      - name: Build with Maven - test
        run: 
          mvn -B --file all-modules-build/pom.xml verify # Ensure all artifacts build successfully before we attempt deploy in order to prevent partial deploys.
        env:
          MAVEN_REPO_USERNAME: build-pipeline
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
      - name: Build with Maven - deploy artifacts
        run:
          mvn -B --file all-modules-build/pom.xml -DskipTests deploy # Now that all builds have completed, we can deploy all the artifacts.
        env:
          MAVEN_REPO_USERNAME: build-pipeline
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
      - name: Build and deploy the docker images
        run:
          mvn -B --file wlan-cloud-opensync-controller/opensync-gateway-static-docker/pom.xml deploy
        env:
          MAVEN_REPO_USERNAME: build-pipeline
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}


